replicaCount: 3  # Az alkalmazás replikáinak száma

image:
  repository: your-dockerhub-username/simple-web-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: web-app
  type: LoadBalancer
  port: 80
  targetPort: 3000
  protocol: TCP
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  allocateLoadBalancerNodePorts: true

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: tesztapp.teszt
      paths:
        - path: /
          pathType: Prefix
  tls: []
