replicaCount: 3  # Az alkalmazás replikáinak száma

image:
  repository: your-dockerhub-username/simple-web-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: tesztapp.teszt
      paths:
        - path: /
          pathType: Prefix
  tls: []
