replicaCount: 3  # Az alkalmazás replikáinak száma

image:
  repository: your-dockerhub-username/simple-web-app
  tag: latest
  pullPolicy: IfNotPresent

mongodb:
  image: mongo:4.4
  replicaSet:
    enabled: true
    name: rs0
  replicaCount: 3  # MongoDB replikák száma
  storageClass: longhorn
  storageSize: 1Gi
  rootUsername: your-root-username  # MongoDB root felhasználónév
  rootPassword: your-root-password  # MongoDB root jelszó
  database: your-database  # MongoDB alapértelmezett adatbázis

service:
  type: ClusterIP
  port: 27017  # MongoDB alapértelmezett portja

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: tesztapp.teszt
      paths:
        - path: /
          pathType: Prefix
  tls: []
