replicaCount: 3  # Az alkalmazás replikáinak száma

image:
  repository: your-dockerhub-username/simple-web-app
  tag: latest
  pullPolicy: IfNotPresent

mariadb:
  host: mariadb-galera
  user: root
  password: 5PqLQBkfDA
  database: mydatabase

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: tesztapp.teszt
      paths:
        - path: /
          pathType: Prefix
  tls: []
