apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mariadb-galera
              key: db_host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-galera
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-galera
              key: mariadb-root-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mariadb-galera
              key: db_name
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
