apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
data:
  mongodb-root-username: {{ .Values.mongodb.rootUsername | b64enc }}
  mongodb-root-password: {{ .Values.mongodb.rootPassword | b64enc }}
